config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :recipes, only: [:new, :create, :destroy, :show, :index, :edit, :update]

  root to: 'welcome#index'

end

app/models/grain.rb
class Grain < ActiveRecord::Base
  belongs_to :recipe
  validates :name, presence: true
  validates :weight, presence: true

  def blank?
    weight.blank? && name.blank?
  end
end

app/models/hop.rb
class Hop < ActiveRecord::Base
  belongs_to :recipe
  validates :name, presence: true
  validates :weight, presence: true
  validates :boil_time, presence: true

  def blank?
    weight.blank? && name.blank? && boil_time.blank?
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :grains, dependent: :destroy do
    # Return the number of open grain spots. Say we have 2 grains already
    # specified for the recipe, then `remaining_capacity` would be 1. (Assuming
    # max capacity is 3 grains).
    # More about Association Extensions:
    # http://guides.rubyonrails.org/association_basics.html#association-extensions
    def remaining_capacity
      max_capacity = 10
      max_capacity - proxy_association.target.size
    end
  end

  has_many :hops, dependent: :destroy do
    def remaining_capacity
      max_capacity = 10
      max_capacity - proxy_association.target.size
    end
  end

  has_many :yeasts, dependent: :destroy do
    def remaining_capacity
      max_capacity = 1
      max_capacity - proxy_association.target.size
    end
  end

  accepts_nested_attributes_for :grains, allow_destroy: true
  accepts_nested_attributes_for :hops, allow_destroy: true
  accepts_nested_attributes_for :yeasts, allow_destroy: true

  before_validation :reject_blank_ingredients

  validates :name, presence: true
  validates :user_id, presence: true
  validates_presence_of :grains,  message: "must include name and weight of at least one grain"
  validates_presence_of :hops,  message: "must fill out all hop fields"
  validates_numericality_of :batch_size
  

  def original_gravity
    brewhouse_efficiency = 0.75
    (((37 * brewhouse_efficiency) / (batch_size / total_grain_weight)) + 1000) / 1000
  end

  def avg_attenuation
    if yeasts.first
      yeasts.average(:attenuation) / 100
    else
      0
    end
  end

  def final_gravity
    avg_attenuation + original_gravity + (-(original_gravity * avg_attenuation))
  end

  def abv
    1.05*(original_gravity-final_gravity)/final_gravity/0.0079;
  end

  def total_grain_weight
    grains.sum(:weight)
  end

  def reject_blank_ingredients
    [grains, hops, yeasts].each do |ingredients|
      ingredients.each do |ingredient|
        if ingredient.blank?
          ingredient.mark_for_destruction
        end
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  has_many :recipes, dependent: :destroy
end

app/models/yeast.rb
class Yeast < ActiveRecord::Base
  belongs_to :recipe

  validates_presence_of :name
  validates_numericality_of :attenuation

  def blank?
    name.blank? || attenuation.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    recipes_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.create(recipe_params)
    if @recipe.save
      flash[:notice] = "Recipe saved."
      redirect_to @recipe
    else
      error_list = "<ul>"
      @recipe.errors.full_messages.each do |error|
        error_list += "<li>#{error}</li>"
      end
      error_list += "</ul>"
      flash[:error] = "There was an error saving your recipe: #{error_list}"
      render :new
    end
  end

  def edit
    record = Recipe.find(params[:id])
    if current_user == record.user
      @recipe = record
    else
      flash[:error] = "You are not authorized to edit this recipe."
      redirect_to root_path
    end
  end

  def update
    record = Recipe.find(params[:id])
    if current_user == record.user
      @recipe = record
      if @recipe.update_attributes(recipe_params)
        flash[:notice] = "Recipe updated."
        redirect_to @recipe
      else
        flash[:error] = "There was an error saving your recipe."
        render :edit
      end
    else
      flash[:error] = "You are not authorized to update this recipe."
      redirect_to root_path
    end
  end

  def destroy
    record = Recipe.find(params[:id])
    if current_user == record.user
      @recipe = record
      if @recipe.destroy
        flash[:notice] = "Recipe deleted."
        redirect_to recipes_path
      else
        flash[:error] = "There was an error deleting your recipe."
        render :edit
      end
    else
      flash[:error] = "You are not authorized to delete this recipe."
      redirect_to @recipe
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def index
    @recipes = Recipe.all
  end

  private

  def recipe_params
    params.require(:recipe).permit(
      :name,
      :style,
      :yeast,
      :summary,
      :notes,
      :batch_size,
      grains_attributes: [:name, :weight, :id],
      hops_attributes: [:name, :weight, :boil_time, :id],
      yeasts_attributes: [:name, :attenuation, :id]
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    redirect_to recipes_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def format_gravity(gravity)
    '%.3f' % gravity
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_nav_links.html.haml
%ul.nav.navbar-nav
  - options.each do |link_text, target|
    - if current_page?(target)
      %li.active= link_to link_text, target
    - else
      %li= link_to link_text, target

app/views/common/_navbar.html.haml
%nav.navbar.navbar-default{role: 'navigation'}
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{type: 'button', "data-toggle" => "collapse", "data-target" => "#bs-example-navbar-collapse-1"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} Brewery

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      = render partial: 'common/nav_links', locals: { options: { "New Recipe" => new_recipe_path, 
      "All Recipes" => recipes_path }}

      %ul.user-info.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle#user-dropdown{ "data-toggle" => "dropdown", role: "button", "aria-expanded" => "false" }
              = (current_user.name || current_user.email)
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li= link_to "Log out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign In", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Brewery
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render partial: 'common/navbar'

    - if flash[:notice]
      .alert.alert-success
        %button.close{type: 'button', "data-dismiss" => 'alert'}
          &times
        = flash[:notice]
    - if flash[:error]
      .alert.alert-danger
        %button.close{type: 'button', "data-dismiss" => 'alert'}
          &times
        = flash[:error].html_safe
    - if flash[:alert]
      .alert.alert-warning
        %button.close{type: 'button', "data-dismiss" => 'alert'}
          &times 
        = flash[:alert]

    .container
      = yield

app/views/recipes/_form.html.haml
.row
  .col-md-8
    = form_for recipe do |form|
      .form-group
        = form.label :name
        = form.text_field :name, autofocus: true, placeholder: 'Name this recipe', class: 'form-control'

      .form-group
        = form.label :style
        = form.text_field :style, placeholder: 'Enter a beer style', class: 'form-control'
    
      - recipe.yeasts.remaining_capacity.times { recipe.yeasts.build }
      = form.label :yeast
      = form.fields_for :yeasts do |yeast_fields|
        .form-group
          = yeast_fields.text_field :name, placeholder: 'Enter a yeast name', class: 'form-control'
          .input-group
            = yeast_fields.number_field :attenuation, placeholder: "Enter the yeast's average attenuation", min: 0.1, step: 0.1, class: 'form-control', 'aria-describedby' => 'basic-addon'
            %span.input-group-addon %

      .form-group
        = form.label :batch_size
        .input-group
          = form.number_field :batch_size, placeholder: 'Enter the batch size in gallons', min: 0.01, step: 0.01, class: 'form-control', 'aria-describedby' => 'basic-addon'
          %span.input-group-addon gal.

      - recipe.grains.remaining_capacity.times { recipe.grains.build }
      = form.label :grains
      .grain-list 
        = form.fields_for :grains do |grain_fields|
          .grain
            .form-group
              = grain_fields.text_field :name, placeholder: "Grain #{grain_fields.index + 1} name", class: 'form-control'
              .input-group
                = grain_fields.number_field :weight, step: 0.05, min: 0.05, placeholder: "Grain #{grain_fields.index + 1} weight", class: 'form-control', 'aria-describedby' => 'basic-addon'
                %span.input-group-addon lbs.
        %button.add-grain.btn.btn-success Add grain

      - recipe.hops.remaining_capacity.times { recipe.hops.build }
      = form.label :hops
      .hop-list
        = form.fields_for :hops do |hop_fields|
          .hop
            .form-group
              = hop_fields.text_field :name, placeholder: "Hop #{hop_fields.index + 1} name", class: 'form-control'
              .input-group
                = hop_fields.number_field :weight, step: 0.05, min: 0.05, placeholder: "Hop #{hop_fields.index + 1} weight", class: 'form-control', 'aria-describedby' => 'basic-addon'
                %span.input-group-addon oz.
              .input-group
                = hop_fields.number_field :boil_time, step: 1, min: 0, placeholder: "Hop #{hop_fields.index + 1} boil time", class: 'form-control', 'aria-describedby' => 'basic-addon'
                %span.input-group-addon min.
        %button.add-hop.btn.btn-success Add hop
      .form-group
        = form.label :summary
        = form.text_field :summary, placeholder: 'Enter a short description of this recipe', class: 'form-control'
      .form-group
        = form.label :notes
        = form.text_field :notes, rows: 4, placeholder: 'Enter any brewing notes', class: 'form-control'
      .form-group
        = form.submit 'Save Recipe', class: 'btn btn-success'

app/views/recipes/edit.html.haml
%h1 Edit Recipe

%ul
  - @recipe.errors.full_messages.each do |error|
    %li
      = error
      
= render partial: 'form', locals: {recipe: @recipe}

app/views/recipes/index.html.haml
%h1 All Recipes

.row
  .col-md-8
    - @recipes.each do |recipe|
      .media
        .media-body
          %h4.media-heading= link_to recipe.name, recipe
          %small= recipe.summary
          %div.recipe-owner
            %em= recipe.user.name

app/views/recipes/new.html.haml
%h1 New Recipe

%ul
  - @recipe.errors.full_messages.each do |error|
    %li
      = error
      
= render partial: 'form', locals: {recipe: @recipe}

app/views/recipes/show.html.haml
.row
  .col-md-8
    %h1= @recipe.name
  .col-md-4
    .btn-group{role: "group"}
      .btn.btn-success= link_to "Edit", edit_recipe_path(@recipe)
      - if current_user == @recipe.user
        .btn.btn-danger= link_to "Delete", @recipe, method: :delete

%p.lead= @recipe.summary

%small Created by #{@recipe.user.name}

.row
  .col-md-6
    %table.table.table-striped
      %tr
        %td Style
        %td #{@recipe.style}
      %tr
        %td Batch Size
        %td #{@recipe.batch_size} gal.
      %tr
        %td Original Gravity
        %td #{format_gravity(@recipe.original_gravity)}
      - if @recipe.yeasts.first
        %tr
          %td Final Gravity
          %td #{format_gravity(@recipe.final_gravity)}
        %tr
          %td ABV
          %td #{'%.2f' % @recipe.abv} %

    %h4 Yeast
    %table.table.table-striped
      - @recipe.yeasts.each do |yeast|
        %tr
          %td= yeast.name
          %td
            #{yeast.attenuation} %

    %h4 Grains
    %table.table.table-striped
      - @recipe.grains.each do |grain|
        %tr
          %td= grain.name
          %td
            #{grain.weight} lbs.
    %h4 Hops
    %table.table.table-striped
      - @recipe.hops.each do |hop|
        %tr
          %td= hop.name
          %td
            #{hop.weight} oz.
          %td
            #{hop.boil_time} min.
    %h4 Notes
    %p #{@recipe.notes}

app/views/welcome/about.html.haml
%h1 Welcome#abouts
%p Find me in app/views/welcome/about.html.erb

app/views/welcome/contact.html.erb
Email me at jpalmieri@lumoslabs.com

app/views/welcome/contact.html.haml
Email me at jpalmieri@lumoslabs.com

app/views/welcome/index.html.haml
.bs-component
  .jumbotron
    %h1 Let's brew, dude!
    %p Welcome to the Brewery, a tool to create and discover homebrew recipes. Click on the button below to sign up and get started with your own recipe, or #{link_to "browse our recipe list", recipes_path}.
    %p.btn.btn-primary.btn-lg= link_to "Sign up", new_user_registration_path